avoid double declaration for vld1q_u8_x4
The missing intrinsic has been added to gcc 7 on Amazon Linux 2, to gcc-8.5, and to gcc-9.4.
Using these compilers to compile sse2neon.h will start failing with multiple definitions of `vld1q_u8_x4`.
`make check` fails with this error on Amazon Linux 2 with gcc-7.3.1-12:

```
g++ -o tests/common.o -Wall -Wcast-qual -I. -march=armv8-a+fp+simd+crc -std=gnu++14 -c -MMD -MF tests/common.o.d tests/common.cpp
In file included from tests/common.h:5:0,
                 from tests/common.cpp:1:
./sse2neon.h: In function ‘uint8x16x4_t vld1q_u8_x4(const uint8_t*)’:
./sse2neon.h:322:27: error: ‘uint8x16x4_t vld1q_u8_x4(const uint8_t*)’ redeclared inline without ‘gnu_inline’ attribute
 FORCE_INLINE uint8x16x4_t vld1q_u8_x4(const uint8_t *p)
                           ^~~~~~~~~~~
In file included from ./sse2neon.h:105:0,
                 from tests/common.h:5,
                 from tests/common.cpp:1:
/usr/lib/gcc/aarch64-redhat-linux/7/include/arm_neon.h:18033:1: note: ‘uint8x16x4_t vld1q_u8_x4(const uint8_t*)’ previously defined here
 vld1q_u8_x4 (const uint8_t *__a)
 ^~~~~~~~~~~
```

I tested this patch with gcc-7.3.1-12 on Amazon Linux 2, and on Ubuntu 20.04 with gcc-9.3 and gcc-10.2.